---
- name: Generate OpenSSH server configuration from template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/80-openssh_config.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart OpenSSH

- name: Ensure OpenSSH service is running
  ansible.builtin.service:
    name: sshd
    state: started

- name: Ensure OpenSSH service is enabled
  ansible.builtin.service:
    name: sshd
    enabled: true
