---
- name: Basic Playbook
  hosts: all
  become: yes

  pre_tasks:
  - name: Update package cache
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
    become: true

  roles:
    - roles/users
    - roles/timezone
    - roles/reboot
